"""Added account table

Revision ID: e42f313294cc
Revises: 
Create Date: 2025-10-15 18:29:37.581535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42f313294cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_by_self', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_by')
    op.drop_column('tasks', 'assigned_by_self')
    # ### end Alembic commands ###
